### ISSUE TITLE
Flickering explanation

### ISSUE THREAD

**Issue by Silex** [OliverF/mjpeg-relay#15]
Hello,

Can you explain a bit what you fought against at https://github.com/OliverF/mjpeg-relay/blob/master/websocketexample.html#L26 ?

I mean, I can understand that some browsers display a bit of blank while the image is rendering, and thus flicker happens  (and probably only *bad* browsers)... what I don't understand is why there are 10 frames :smile:

Wouldn't 2 be sufficient?

**Comment by OliverF** [comment]
Hello!

That was a long time ago, from memory I think that was because 2 wasn't sufficient to prevent flickering at high FPS and high resolution. I don't have such a stream to test with right now but I recall a bit of trial and error, plus some margin for extra "safety", lead to the number of 10. I'm not sure why the flickering happened at such a high number of buffer frames, if I'm honest. I too was surprised by the fact it required more than 2. I never found an explanation, but I remember it irked me for a while. If you stumble upon a lower number that works at high FPS and resolutions, or an explanation of why this happens, please let me know!

Well spotted :)

**Comment by Silex** [comment]
Well, in the meantime I did it differently.

You are doing this:

``` javascript
newFrame.onload = imageOnload;
newFrame.src = evt.data;
```

This has this effect with high FPS:

```
[frame1] received from websocket
[frame1] set "onload" and apply src
[frame2] received from websocket
[frame2] set "onload" and apply src
[frame3] received from websocket
[frame3] set "onload" and apply src
[frame1] onload event firing
[frame4] received from websocket
[frame4] set "onload" and apply src
[frame2] onload event firing
[frame5] received from websocket
[frame5] set "onload" and apply src
[frame3] onload event firing
[frame6] received from websocket
[frame6] set "onload" and apply src
...
```

As you see, you constantly have N frames being loaded in parallel. This is silly as the browser can only render one of them.

It needs to be done differently, pseudo code would be like:

``` javascript
var img = $('img');
var loading = false;

img.onload = function imageOnload()
{
   loading = false;
}

function onMessage(evt)
{
   if (!loading)
   {
     loading = true;
     img.src = evt.data;
   }
}
```

I'll see if I can make a PR.

**Comment by OliverF** [comment]
Just a couple of thoughts

1. This new way would drop frames if the browser can't keep up - I think this is preferable to creating a backlog of frames so sounds good. But this only makes sense under the assumption that the browser can only render 1 frame at a time:
2. Can the browser only render 1 frame at a time? There is some time between receiving the data from the WebSocket and displaying it on the screen, which is what I presume you mean when you say rendering. You'll have to excuse me as this is where my knowledge has gaps, but is there necessarily only 1 image being rendered at a time? The idea with the current way is that whilst 1 frame is rendering, we can receive a new frame and start rendering that. We might have a buffer of 10 or so frames due to the initial overheads, if the framerate is fast enough, but provided the browser/client can keep up, we'd like to make use of rendering multiple frames at once.

I can't implement your idea right now to test so this is all speculation from me. If you do end up testing please let me know the outcome!

**Comment by Silex** [comment]
Ah!

I thought your code was a workaround for the fact that if you constantly change an image src, flickering happens (at least on firefox, chrome seems ok). And thus I wondered why you needed 10 frames and not only 2 (hence my original question).

Your implementation makes a lot more sense now, basically what you do is paralellize the "render" part, that way the "display" FPS is more or less equal as the one of the "frame receive" FPS.

Okay then, scratch pretty much everything I said. That said I think we can modify it a bit so it does not use a framebuffer, but simply when one frame renders it deletes the ones that it did hide. You're currently using `zindex` to bring an image on top, but maybe `display` or `visibility` are more efficient. I wonder if there's an event for "finished rendering" :smile: that would help a lot.

**Comment by Silex** [comment]
http://stackoverflow.com/questions/14578356/how-to-detect-when-an-image-has-finished-rendering-in-the-browser-i-e-painted and http://jsfiddle.net/4fg3K/1/ might help.

**Comment by strayer** [comment]
I'm currently experimenting with canvas and drawImage… it works fine for now and the CPU usage decreased from 10% to 5% (loading the mjpeg stream directly from source uses 7-8%, so the canvas is actually even faster).

As far as I understand this fixes the flickering issue as a side-effect because the new image is always drawn above the last image and also only when it is fully loaded.

**Comment by OliverF** [comment]
Forgot to close in the merge commit message: this was fixed/resolved by Strayer in:
https://github.com/OliverF/mjpeg-relay/commit/b87d1c25d0876b067de68fe51a418d559f67beb4

Many thanks for the contribution!
